export interface Project {
  id: string;
  name: string;
  architect: string;
  location: string;
  year: string;
  matchPercentage?: number;
  imageUrl: string;
  url?: string; // Alias for imageUrl
  style: string[];
  buildingType: string;
  typology?: string; // Alias for buildingType
  scale: "Small" | "Medium" | "Large";
  climate: string[];
  materials?: string[]; // Alias for style
  yearBuilt: number;
  architectNationality: string;
  keywords: string[];
}

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Louvre Abu Dhabi",
    architect: "Jean Nouvel",
    location: "Abu Dhabi",
    year: "2017",
    matchPercentage: 87,
    imageUrl: "https://images.unsplash.com/photo-1659733078034-e72628a66420?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBtdXNldW0lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzYxNTQ3NTI4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Parametric"],
    buildingType: "Cultural",
    scale: "Large",
    climate: ["Arid / Hot-Dry"],
    yearBuilt: 2017,
    architectNationality: "French",
    keywords: ["dome", "geometric", "light filtering", "water feature"],
  },
  {
    id: "2",
    name: "Salk Institute",
    architect: "Louis Kahn",
    location: "La Jolla",
    year: "1965",
    matchPercentage: 82,
    imageUrl: "https://images.unsplash.com/photo-1677161795040-7cf4d7007312?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicnV0YWxpc3QlMjBjb25jcmV0ZSUyMGJ1aWxkaW5nfGVufDF8fHx8MTc2MTUwOTM5MHww&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Brutalist", "Modern"],
    buildingType: "Educational",
    scale: "Medium",
    climate: ["Temperate"],
    yearBuilt: 1965,
    architectNationality: "American",
    keywords: ["concrete", "courtyard", "symmetry", "monumental"],
  },
  {
    id: "3",
    name: "Ningbo Historic Museum",
    architect: "Wang Shu",
    location: "Ningbo",
    year: "2008",
    matchPercentage: 79,
    imageUrl: "https://images.unsplash.com/photo-1657896323372-dda720c48d00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjBtdXNldW0lMjBidWlsZGluZ3xlbnwxfHx8fDE3NjE1ODkxODN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Traditional"],
    buildingType: "Cultural",
    scale: "Medium",
    climate: ["Temperate"],
    yearBuilt: 2008,
    architectNationality: "Chinese",
    keywords: ["recycled materials", "vernacular", "brick", "contextual"],
  },
  {
    id: "4",
    name: "The Broad Museum",
    architect: "Diller Scofidio + Renfro",
    location: "Los Angeles",
    year: "2015",
    matchPercentage: 76,
    imageUrl: "https://images.unsplash.com/photo-1534094830444-3a1e21f7e3e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwYXJjaGl0ZWN0dXJlfGVufDF8fHx8MTc2MTU4ODk4MHww&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Parametric"],
    buildingType: "Cultural",
    scale: "Medium",
    climate: ["Arid / Hot-Dry"],
    yearBuilt: 2015,
    architectNationality: "American",
    keywords: ["honeycomb facade", "veil", "natural light", "urban"],
  },
  {
    id: "5",
    name: "Chichu Art Museum",
    architect: "Tadao Ando",
    location: "Naoshima",
    year: "2004",
    matchPercentage: 74,
    imageUrl: "https://images.unsplash.com/photo-1531626155160-d56b8230eba7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXJhbWV0cmljJTIwZmFjYWRlJTIwYnVpbGRpbmd8ZW58MXx8fHwxNzYxNTg5MTgzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Minimalist", "Contemporary"],
    buildingType: "Cultural",
    scale: "Small",
    climate: ["Temperate"],
    yearBuilt: 2004,
    architectNationality: "Japanese",
    keywords: ["underground", "concrete", "natural light", "spiritual"],
  },
  {
    id: "6",
    name: "Museo Soumaya",
    architect: "Fernando Romero",
    location: "Mexico City",
    year: "2011",
    matchPercentage: 71,
    imageUrl: "https://images.unsplash.com/photo-1684403798148-cf48281bdf8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBsaWJyYXJ5JTIwYXJjaGl0ZWN0dXJlfGVufDF8fHx8MTc2MTQ4OTA5NHww&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Parametric", "Contemporary"],
    buildingType: "Cultural",
    scale: "Medium",
    climate: ["Temperate"],
    yearBuilt: 2011,
    architectNationality: "Mexican",
    keywords: ["aluminum", "sculptural", "irregular form", "reflective"],
  },
  {
    id: "7",
    name: "Seattle Central Library",
    architect: "OMA / Rem Koolhaas",
    location: "Seattle",
    year: "2004",
    matchPercentage: 69,
    imageUrl: "https://images.unsplash.com/photo-1642775653775-d00324a03233?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjBjdWx0dXJhbCUyMGNlbnRlcnxlbnwxfHx8fDE3NjE1ODkxODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Parametric"],
    buildingType: "Cultural",
    scale: "Large",
    climate: ["Temperate"],
    yearBuilt: 2004,
    architectNationality: "Dutch",
    keywords: ["diagrid", "glass", "cantilevered", "innovative"],
  },
  {
    id: "8",
    name: "Therme Vals",
    architect: "Peter Zumthor",
    location: "Vals",
    year: "1996",
    matchPercentage: 67,
    imageUrl: "https://images.unsplash.com/photo-1617182726501-1f5f7b05a68f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzcGElMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzYxNTg5MTg0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Minimalist", "Contemporary"],
    buildingType: "Commercial",
    scale: "Small",
    climate: ["Continental"],
    yearBuilt: 1996,
    architectNationality: "Swiss",
    keywords: ["stone", "thermal baths", "sensory", "layered"],
  },
  {
    id: "9",
    name: "Kanagawa Institute of Technology",
    architect: "Junya Ishigami",
    location: "Kanagawa",
    year: "2008",
    matchPercentage: 65,
    imageUrl: "https://images.unsplash.com/photo-1759441876689-aa8e847a3ae3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwZWR1Y2F0aW9uYWwlMjBidWlsZGluZ3xlbnwxfHx8fDE3NjE1ODkxODR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Minimalist", "Contemporary"],
    buildingType: "Educational",
    scale: "Medium",
    climate: ["Temperate"],
    yearBuilt: 2008,
    architectNationality: "Japanese",
    keywords: ["thin columns", "forest-like", "transparent", "delicate"],
  },
  {
    id: "10",
    name: "Copenhagen International School",
    architect: "C.F. Møller Architects",
    location: "Copenhagen",
    year: "2017",
    matchPercentage: 63,
    imageUrl: "https://images.unsplash.com/photo-1603958956194-cf9718dba4b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzY2hvb2wlMjBidWlsZGluZ3xlbnwxfHx8fDE3NjE1MzE4ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Modern"],
    buildingType: "Educational",
    scale: "Large",
    climate: ["Temperate"],
    yearBuilt: 2017,
    architectNationality: "Danish",
    keywords: ["solar panels", "sustainable", "blue facade", "waterfront"],
  },
  {
    id: "11",
    name: "8 House",
    architect: "BIG - Bjarke Ingels Group",
    location: "Copenhagen",
    year: "2010",
    matchPercentage: 61,
    imageUrl: "https://images.unsplash.com/photo-1711203605191-d879424e7ec2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXNpZGVudGlhbCUyMGFwYXJ0bWVudCUyMGZhY2FkZXxlbnwxfHx8fDE3NjE1ODkyNTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Parametric"],
    buildingType: "Residential",
    scale: "Large",
    climate: ["Temperate"],
    yearBuilt: 2010,
    architectNationality: "Danish",
    keywords: ["mixed-use", "continuous loop", "balconies", "innovative"],
  },
  {
    id: "12",
    name: "Apple Park",
    architect: "Foster + Partners",
    location: "Cupertino",
    year: "2017",
    matchPercentage: 59,
    imageUrl: "https://images.unsplash.com/photo-1703355685722-2996b01483be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjBvZmZpY2UlMjBidWlsZGluZ3xlbnwxfHx8fDE3NjE1ODkyNTJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Modern"],
    buildingType: "Commercial",
    scale: "Large",
    climate: ["Temperate"],
    yearBuilt: 2017,
    architectNationality: "British",
    keywords: ["circular", "glass", "landscaped", "tech campus"],
  },
  {
    id: "13",
    name: "Elbphilharmonie Hamburg",
    architect: "Herzog & de Meuron",
    location: "Hamburg",
    year: "2016",
    matchPercentage: 57,
    imageUrl: "https://images.unsplash.com/photo-1721058677688-4c924504a7a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdWx0dXJhbCUyMGNlbnRlciUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NjE1NzI5NTR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Parametric"],
    buildingType: "Cultural",
    scale: "Large",
    climate: ["Temperate"],
    yearBuilt: 2016,
    architectNationality: "Swiss",
    keywords: ["glass wave", "adaptive reuse", "harbor", "crystalline"],
  },
  {
    id: "14",
    name: "Chapel of Sound",
    architect: "OPEN Architecture",
    location: "Beijing",
    year: "2021",
    matchPercentage: 55,
    imageUrl: "https://images.unsplash.com/photo-1759416797559-c14b8ba12fe6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjByZWxpZ2lvdXMlMjBidWlsZGluZ3xlbnwxfHx8fDE3NjE1ODkyNTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Minimalist"],
    buildingType: "Infrastructure",
    scale: "Small",
    climate: ["Continental"],
    yearBuilt: 2021,
    architectNationality: "Chinese",
    keywords: ["amphitheater", "landscape integration", "acoustic", "stone"],
  },
  {
    id: "15",
    name: "MPavilion",
    architect: "Studio Mumbai",
    location: "Melbourne",
    year: "2016",
    matchPercentage: 53,
    imageUrl: "https://images.unsplash.com/photo-1619509800519-dd8010775e07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXZpbGlvbiUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NjE1MzQ5Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    style: ["Contemporary", "Traditional"],
    buildingType: "Cultural",
    scale: "Small",
    climate: ["Temperate"],
    yearBuilt: 2016,
    architectNationality: "Indian",
    keywords: ["timber", "craftsmanship", "temporary", "vernacular"],
  },
];
